### ISSUE TITLE
Create code of conduct in repo

### ISSUE THREAD

**Issue by gaborbuzasi** [gaborbuzasi/group-b-sem-coursework#1]

**Comment by PrincessC96** [comment]
https://docs.google.com/document/d/14S082rXp-3fvxjstQoS0H-2eW90SPWLH5KpeHNnULBA/edit 
Code of conduct in the above document. Issue can be closed

**Comment by PrincessC96** [comment]
I have uploaded the code of conduct. This was created by the group in a collaborative meeting and word processed by me.

**Comment by gaborbuzasi** [comment]
Created
